// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mguwnpsyxjdfpgznqjxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ndXducHN5eGpkZnBnem5xanhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwMzMxNDEsImV4cCI6MjA3MTYwOTE0MX0.zTSzZhSU2kiNO2R6-UBMT8mJYr_onkbKNIa4dbIVGGw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});